server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://eureka-discovery:9001/eureka

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

spring:
#  datasource:
#    url: jdbc:mysql://mysql:3306/db_incidents
#    username: root
#    password: root

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: vault://

  cloud:
    vault:
      authentication: TOKEN
      token: ${HASHICORP_VAULT_ROOT_TOKEN}
      uri: http://hashicorp-vault:8200
      kv:
        backend: secretsKV
        default-context: pisio

aws:
  region: eu-central-1
  bucket-name: pisio-incidents-aws-storage
  credentials:
    access-key-id: ${S3_BUCKET_ACCESS_KEY}
    secret-access-key: ${S3_BUCKET_SECRET_KEY}

rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
  exchange: incident-exchange
  queue-incident-created: incident-created-queue
  queue-status-updated: status-updated-queue
  routing-key-incident-created: incident.created
  routing-key-status-updated: incident.status.updated

translation:
  url: https://translation.googleapis.com/language/translate/v2
  api-key: ${GOOGLE_TRANSLATION_API_KEY}