server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://eureka-discovery:9001/eureka


spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql:3306/db_incidents
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
  cloud:
    vault:
      authentication: TOKEN
      token: ${HASHICORP_VAULT_ROOT_TOKEN}
      uri: http://hashicorp-vault:8200
      kv:
        backend: secretsKV
        default-context: pisio

oauth2:
  client:
    registration:
      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}

jwt:
  # 10 minutes
  access-token-expiration: 600000
  # 7 days
  refresh-token-expiration: 604800000
  # 512b key
  secret-key: ${JWT_SECRET_KEY}
