eureka:
  instance:
    hostname: localhost
    port: 9001
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_incidents
    username: root
    password: toor

  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql

  cloud:
    vault:
      authentication: TOKEN
      token: ${HASHICORP_VAULT_ROOT_TOKEN}
      uri: http://localhost:8200
      kv:
        backend: secretsKV
        default-context: pisio

oauth2:
  client:
    registration:
      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}

jwt:
  # 10 minutes
  access-token-expiration: 600000
  # 7 days
  refresh-token-expiration: 604800000
  # 512b key
  secret-key: ${JWT_SECRET_KEY}
