server:
  port: 9002

eureka:
  instance:
    hostname: localhost
    port: 9001
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            - id: incident-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/incidents/**
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/auth/**, /login/**, /default-ui.css
            - id: moderation-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/moderation/**
            - id: analytics-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/analytics/**


# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

jwt:
  # 10 minutes
  access-token-expiration: 600000
  # 7 days
  refresh-token-expiration: 604800000
  # 512b key
  secret-key: ${JWT_SECRET_KEY}


# if load balancer implemented
#        routes:
#            - id: incident-service
#              uri: lb://incident-service
#              predicates:
#                - Path=/api/v1/incidents/**
#              filters:
#                - StripPrefix=1
#            - id: auth-service
#              uri: lb://auth-service
#              predicates:
#                - Path=/api/v1/auth/**, /login/**, /default-ui.css
#              filters:
#                - StripPrefix=1
#            - id: moderation-service
#              uri: lb://moderation-service
#              predicates:
#                - Path=/api/v1/moderation/**
#              filters:
#                - StripPrefix=1